### ISSUE TITLE
Secrets with different probabilities

### ISSUE THREAD

**Issue by mattgig** [mattgig/GIFT-for-Stash#4]
At the moment when generating quiz questions to use Stash secrets, all of them have the same probability to be used.

Is there a real need to implement a feature which allows different probabilities?

In case somebody really needs this feature, wouldn't it be easier to just add a certain secret several times to increase its likelihood to make it into one of the options of a question?

Please discuss.

**Comment by fdagner** [comment]
With different probabilities, entering the codes is more user-friendly and easier to follow. It should perhaps be an additional function that is unlocked with a button.

**Comment by wwobble** [comment]
For a few codes it wil be easy to add one code multiple times to make it more likely but with a lot of different codes it will be difficult to keep track of how often which code is in the array. 
The option to give different probabilities is nessacary for so many things, so it should be a feature. Every trading card game or other collecting game (like Panini) that works with buying pack of objects (like booster) benefits of the fact that you have objects that you will have multiple times and rare objects that you try to find and which keep you going (buying) to collect all of them. So I would like to have that option to get my students addicted like I was with pokemon and magic cards and Dragonball Stickers ;-) 

The con argument of a more complicated input because you have to give an additional informationen (probability) could be avoided by import of a CSV and something in the code that checks if there is a column for the number how often the code should be added and if not it sets it to 1.  So it would be an optional feature.

**Comment by fdagner** [comment]
I don't know if I understood that completely. Here is an experimental version where you can set the number of codes in the array. It is not yet implemented in the import function.

[GIFT_for_stash.zip](https://github.com/mattgig/GIFT-for-Stash/files/11471714/GIFT_for_stash.zip)

**Comment by fdagner** [comment]
The import function is now integrated. Weighting is separated with comma. File would be ready for merge. I am excited about your feedback.

[GIFT_for_stash.zip](https://github.com/mattgig/GIFT-for-Stash/files/11472696/GIFT_for_stash.zip)

**Comment by mattgig** [comment]
Thank you for your contribution. I've merged your suggested solution.
